server:
  servlet:
    port: 8080
    contextPath: /api

spring:

  application:
    name: movieapp-api

  datasource:
    url: jdbc:postgresql://postgresdb.cnslxnballye.us-east-1.rds.amazonaws.com:5432/postgresdb
    username: postgres
    password: postgres@123

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
